### ISSUE TITLE
Introduce configuration file

### ISSUE THREAD

**Issue by ligurio** [ligurio/unreliablefs#3]
**Possible formats:**

- JSON (https://github.com/zserge/jsmn)
- INI
  - https://github.com/mariusae/trickle/blob/master/conf.c
  - https://github.com/benhoyt/inih
- XML

**Configuration file should have number of sections each of them describes:**

- field with type of fault injection:
  - [ ] `errinj_remove` (see #35)
  - [ ] `errinj_truncate` (see #34)
  - [ ] `errinj_kill_caller` kill process that run operation (see #28)
  - [ ] `errinj_incomplete_write` incomplete writes (see #27)
  - [ ] `errinj_corrupted_write` corrupted writes (see #8)
  - [ ] `errinj_errno` (random or fixed) (+ regex that describes what errors one desired to return) (see #6 #9) 
  - [ ] `errinj_noop` replace operation with no-op for those operations where it possible (see #18)
  - [ ] `errinj_delayed_op` delay on operations (see #29)
  - [ ] `errinj_clear_cache` (see #57)
- field with probability (0-100%)
- field with regexp for filesystem path where fault injection should happen

For example:
```
[errinj_errno]
path_regexp = *.xlog
operation_regexp =
probability = 60

[errinj_noop]
path_regexp = *.*
operation_regexp =
probability = 30
```
